# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    param_fetcher_listener:  true
    allowed_methods_listener:  true
    routing_loader: false
    view:
        view_response_listener:  true
    exception:
        codes:
          Symfony\Component\Routing\Exception\ResourceNotFoundException: 404
          InvalidArgumentException: 400
          Doctrine\ORM\OptimisticLockException: HTTP_CONFLICT
#        messages:
#            App\Exception\MyException: Forbidden area.
    format_listener:
        rules:
            - { path: ^/, prefer_extension: false, fallback_format: json, priorities: [ json, html ] }
    body_converter:
      enabled: true