version: '3.3'
services:
    nginx:
        image: nginx:1.15
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        links:
            - php

    php:
        build: .docker/php
        volumes:
            - ./:/var/www/
            - .docker/php/php.ini:/usr/local/etc/php/php.ini
        links:
            - mysql

    mysql:
        image: mysql:5.7
        volumes:
            - mysql_data:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
            MYSQL_USER: bts
            MYSQL_PASSWORD: bts
            MYSQL_DATABASE: bts


volumes:
    mysql_data:

